const loremIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in odio dolor. Mauris et libero diam. Curabitur vitae ligula porta, lacinia sem eu, consequat ligula. Aenean congue vestibulum purus, eget elementum libero pretium at. Sed fermentum pharetra ipsum, in efficitur risus vestibulum at. Cras porta iaculis libero, eget pharetra urna lacinia vel. Morbi nec tortor sem. Donec finibus placerat ligula, id laoreet magna. Etiam non tortor dapibus, facilisis elit vitae, molestie nunc." +

"Donec sodales rhoncus arcu, tristique pretium nibh commodo vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum accumsan, leo ac egestas varius, arcu felis varius ex, id efficitur augue mauris at enim. Duis vel vestibulum augue, sit amet volutpat dolor. Maecenas odio ligula, egestas vel vulputate et, scelerisque aliquam elit. Cras pellentesque, tortor sed dapibus bibendum, lacus eros sollicitudin enim, in porttitor nulla est placerat dui. Aliquam interdum urna ac lacus viverra, et dapibus urna elementum. Suspendisse condimentum dignissim iaculis. Phasellus quis sapien neque. Fusce quis orci in justo ultricies pellentesque ut nec ligula. Phasellus imperdiet iaculis arcu, sed scelerisque ex suscipit nec." +

"Aliquam ante lacus, condimentum id vestibulum eget, bibendum sit amet dolor. Proin id ornare eros. Aenean non elit nisi. Curabitur in mi ac purus vulputate volutpat at quis odio. Sed vitae facilisis elit. Maecenas molestie nunc non mauris gravida, at convallis orci dictum. Aliquam aliquet turpis sit amet feugiat ultricies. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam sed massa cursus, efficitur orci a, pretium mi. Phasellus mi sapien, molestie a cursus hendrerit, aliquet at metus. Morbi mattis est eget neque rutrum blandit. Nam at erat ultrices, tristique nisi in, fringilla velit. Fusce commodo malesuada nisi at laoreet. Morbi ac orci odio. Cras consequat purus quis risus porta, vitae viverra diam viverra." +

"Duis efficitur condimentum sem, mattis accumsan elit mollis id. Integer nec vulputate justo, vel interdum felis. Nam ut vestibulum nisi. Quisque fringilla, lacus vitae facilisis faucibus, orci orci vehicula est, at pretium nisi dui vitae ex. Sed vitae consequat felis. Cras nec massa quis erat porttitor efficitur quis ac velit. Donec ut orci nibh. Donec tempor nisl massa, non dapibus orci mattis id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus." +

"Phasellus quis nibh pharetra, pretium massa et, iaculis lectus. Duis imperdiet enim lacus, sed fringilla leo euismod at. Cras consectetur lectus dignissim, rutrum eros nec, iaculis velit. Ut nec mi in risus vulputate euismod et quis massa. Curabitur eu velit mattis lectus ullamcorper finibus. Suspendisse in pulvinar tellus. Nam id elit volutpat, fermentum lacus at, feugiat diam. Pellentesque finibus, lorem in fringilla vulputate, ligula ipsum congue dolor, in cursus tortor nisi nec nunc. Curabitur scelerisque odio felis, vel condimentum odio fringilla non. Ut gravida mi id nibh porta tristique. Cras sit amet feugiat ligula. Quisque in risus eros. Nam interdum at massa sed elementum.";

function getLoremIpsum(numChars){
    return loremIpsum.substring(0, numChars);
}
